<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_gender</name>
   <tag></tag>
   <elementGuidId>ebb1ae7a-364a-4cde-986e-902cec7b1dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#male</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='male']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd54efef-634e-4bc5-9067-56d5ec85100c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4960bb1f-5423-4c11-a817-a8dd4ea14734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>9e110bb9-b450-46a5-99ea-e083f9619f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>f7a2d46c-29c5-4f9f-aed4-7cadd3643079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>055323a2-9916-4cf0-b545-9e455b02efd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;male&quot;)</value>
      <webElementGuid>13d3e5c2-bd8c-4c13-9e2d-f20c159cd53a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='male']</value>
      <webElementGuid>ca16663c-017f-4bf4-a773-1623259776a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input[3]</value>
      <webElementGuid>fe64d082-4b05-4488-8af9-9d6a0b199e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'male' and @name = 'gender']</value>
      <webElementGuid>a121b6d4-4d68-4ff5-b370-dfee6273a11d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
