<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start typing and it till automaticall_25c4d8</name>
   <tag></tag>
   <elementGuidId>42894d59-c9c3-448a-b07b-a2da55660d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Options&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Options']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70be2a1a-1164-433c-8518-be0fc80a1fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>datalists</value>
      <webElementGuid>9221f16c-54ad-4da1-96e6-a3ffc906409f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Options</value>
      <webElementGuid>e9957d0b-5dcd-4ca2-8e6f-979e5f48835d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;row&quot;]/div[@class=&quot;main&quot;]/form[1]/fieldset[1]/input[9]</value>
      <webElementGuid>d28773e7-0cf0-46ce-a2ba-e2aaf5283d8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Options']</value>
      <webElementGuid>da4d26fd-4e16-44de-ac3a-8152244f29cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>2fc68487-052e-4f3b-b0e7-4c95cfe8835d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Options']</value>
      <webElementGuid>69022ab2-1d69-4c4d-9b08-267416fa6f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
