<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_lname</name>
   <tag></tag>
   <elementGuidId>d75f6e28-4fa3-4b51-a8e7-367cb50445bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>617e2902-2536-4f6c-bfcb-3644ceda7608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6b8b62a-1d21-4e9c-bf87-3c0ac3ab23d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>493cc522-73b1-495e-b990-cdcdaf7c7478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>1e5ecd1f-a983-4dea-8cf2-eac36a64dd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lname</value>
      <webElementGuid>4f7172ef-c595-4af2-8c2a-7957098674b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lname&quot;)</value>
      <webElementGuid>f2c87701-46b9-43bb-a4ba-221cabade0a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lname']</value>
      <webElementGuid>51ce900f-51dd-4c03-8a85-2b16a185840a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input[2]</value>
      <webElementGuid>bae5527c-9890-49c3-866d-526931cec799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lname' and @placeholder = 'Text' and @name = 'lname']</value>
      <webElementGuid>d42c63b3-37b7-47a0-bf63-24edf81fe824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
